export const INCREMENT_BREAK_LENGTH = "INCREMENT_BREAK_LENGTH";

export const DECREMENT_BREAK_LENGTH = "DECREMENT_BREAK_LENGTH";

export const INCREMENT_SESSION_LENGTH = "INCREMENT_SESSION_LENGTH";

export const DECREMENT_SESSION_LENGTH = "DECREMENT_SESSION_LENGTH";

export const SESSION_LENGTH_CHANGED = "SESSION_LENGTH_CHANGED";

export const DECREMENT_SESSION_TIMER = "DECREMENT_SESSION_TIMER";

export const SESSION_COMPLETED = "SESSION_COMPLETED";
